version: '3.9'

services:
  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    ports:
      - 8081:8050

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    ports:
      - 8083:8050

  sc-verifier:
    extends:
      file: ./services/smart-contract-verifier.yml
      service: smart-contract-verifier
    ports:
      - 8082:8050

  stats:
    extends:
      file: ./services/stats.yml
      service: stats
    ports:
      - 8080:8050

  user-ops-indexer:
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
