services:
  rpcplorer:
    container_name: golembase-rpcplorer
    depends_on:
      op-geth:
        condition: service_healthy
    image: dmilhdef/rpcplorer:v0.0.1
    ports:
      - 8088:8080
    environment:
      - NODE_URL=http://op-geth:8545
    restart: on-failure